version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_DSN: postgres://user:password@postgres:5432/moviedb
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: moviedb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: